# BPI Repossessed Cars (PDF)

In [1]:
!pip install PyMuPDF pandas

Collecting PyMuPDF
  Downloading PyMuPDF-1.24.5-cp310-none-manylinux2014_x86_64.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 9.0 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Collecting PyMuPDFb==1.24.3 (from PyMuPDF)
  Downloading PyMuPDFb-1.24.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (15.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 24.1 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: PyMuPDFb, PyMuPDF
Successfully installed PyMuPDF-1.24.5 PyMuPDFb-1.24.3

In [2]:
import fitz
import re
import pandas as pd

## Read PDF File

In [33]:
pdf_document = '/content/drive/MyDrive/Webscraping Datasets (BPI)/cagayan_de_oro.pdf'
pdf = fitz.open(pdf_document)

## Extract Text

In [34]:
text = ""
for page_num in range(len(pdf)):
    page = pdf.load_page(page_num)
    text += page.get_text()
text

"REG BIDDING\nBID NOW\nPRICE\nPRICE\n2021 SUZUKI ERTIGA M/T 1.5 GL   \n29,155\nJAK7175\nGRAY\n532,707\n585,978\n2020 NISSAN  URVAN M/T 2.5 0  (D)  [ Broken front \nwindshield ]\n349,273\nJAD9285\nWHITE\n478,035\n525,838\n2019 MITSUBISHI STRADA M/T 2.4 GLS 4X2 (D)                                               \n[ UNENCUMBERED CR AND UNANNOTATED PNCM  ]\n5,914\nKAD5720\nSILVER\n558,390\n614,229\n2018 MITSUBISHI MONTERO  A/T 2.4 GLS 4X2 (D)                                  \n[ UNENCUMBERED CR AND UNANNOTATED PNCM, missing \ntail/stoplight ]\n41,658\nNO PLATE\nBLUE\n789,889\n868,878\n2019 NISSAN  NAVARA A/T 2.5 EL 4X2 (D)  [ UNABLE TO \nOPEN HOOD  ]\n83,689\nJAH8296\nBROWN\n564,340\n620,774\n2022 MG MG5 M/T 1.5  [ UNENCUMBERED CR AND \nUNANNOTATED PNCM  ]\n13,967\nLAK5451\nWHITE\n315,140\n346,654\n2020 TOYOTA  VIOS M/T 1.3 J   [ BROKEN LEFT TAILIGHT \n, POOR TRUNK LID CONDITION. UNENCUMBERED CR  ]\n145,534\nGAO1646\nWHITE\n294,724\n324,197\n2018 MITSUBISHI MIRAGE G4 A/T 1.2 GLX   [ BROKEN \nLEFT TAILIGHT AND LEFT HEADLIGHT, UNENCUMBERED CR  ]\n55,730\nKAB8123\nGRAY\n261,064\n287,171\n2020 CHEVROLET  COLORADO  A/T 2.8 TRAIL BOSS 4X2 \n(D) [ NO SPARE TIRE & TOOLS ]\n117,640\nKAF8625\nBROWN\n583,977\n642,374\n2023 KIA SOLUTO A/T 1.4 LX   [ UNENCUMBERED CR  ]\n9,729\nXOT739\nBEIGE\n420,210\n462,231\n2021 TOYOTA  VIOS A/T 1.3 XLE   [ WITH 1 LETTER \nDIFFERENCE IN ACTUAL PLATE NUMBER AND CR PLATE NUMBER ]\n76,735\nGAU8837\nSILVER\n485,959\n534,555\n2016 FOTON TORNADO  M/T 4.5 DROPSIDE 4X2 (D)                                      \n[ UNENCUMBERED CR , BROKEN DOOR LOCKS  ]\n85,405\nKAA1291\nWHITE\n259,910\n285,901\n2019 CHEVROLET  COLORADO  M/T 2.5 LT 4X2 (D)                                     \n[ UNENCUMBERED CR, BROKEN TRUN K DOOR  ]\n91,966\nFAG5565\nSILVER\n511,056\n562,162\n2020 MG  MG5 A/T 1.5   [ FRONT BUMPER COLLISION  ]\n34,858\nNGD2252\nBLUE\n321,580\n353,738\n2016 HYUNDAI  EON M/T 0.8 GLX   [ WITH 1 LETTER \nDIFFERENCE IN ACTUAL PLATE NUMBER AND CR PLATE NUMBER ]\n11,904\nKDO6435\nRED\n176,656\n194,322\n2018 FORD RANGER A/T 2.2 0 4X2 (D) [ MINOR \nSCRATCHES ]\n113,683\nZAA8101\nBLACK\n557,480\n613,228\n2020 KIA  SOLUTO M/T 1.4 LX   [ Unencumbered CR; \nAnnotated PNCM ]\n79,880\nKAD4511\nWHITE\n209,790\n230,769\n2020 FORD  ECOSPORT  M/T 1.5 TREND   \n11,980\nZAB7982\nRED\n425,600\n468,160\n2017 MITSUBISHI  MIRAGE G4 M/T 1.2 GLX                                                 \n[ Unannotated PNCM and Unencumbered CR  ]\n46,406\nKAB4954\nRED\n258,700\n284,570\n2022 MITSUBISHI MIRAGE G4 A/T 1.2 GLX                                             \n[ UNANNOTATED PNCM  ]\n10,595\nNFK6246\nRED\n475,006\n522,507\n2019 Hyundai  Accent M/T 1.4 GL   [ BROKEN FRONT \nBUMPER AND TRUNK LID RUSTING ]\n76,127\nJAC7712\nWHITE\n221,520\n243,672\n2021 TOYOTA  VIOS A/T 1.3 XLE    \n25,544\nGAV7392\nGARYISH BLUE\n537,263\n590,989\n2021 GEELY COOLRAY  A/T 1.5 SPORTS   \n28,133\nFAI3602\nRED\n602,980\n663,278\n2020 CHEVROLET  COLORADO A/T 2.8 LTZ 4X4 (D)                           \n[Broken Front bumper and side fender. Slightly broken rear bumper]\n88,788\nKAG1209\nWHITE\n596,505\n656,156\n2019 MG ZS A/T 1.5 STYLE   \n41,578\nFAG1543\nORANGE\n406,840\n447,524\n2020 NISSAN  ALMERA A/T 1.2 LE   [ Unannotated PNCM \nand unencumbered CR  ]\n95,025\nKAF8718\nBROWN\n269,368\n296,305\n2022 MG MG5 M/T 1.5   [ Broken driver's side door lock, \nBroken front Right window side  ]\n21,786\nLAK3170\nRED\n309,725\n340,698\n2023 NISSAN  LIVINA A/T 1.5 VE   \n18,370\nGAK4191\nSILVER\n725,970\n798,567\n2022 MITSUBISHI MIRAGE G4 M/T 1.2 GLX                                            \n[ Unannotated PNCM and unencumbered CR  ]\n19,810\nKAP5148\nSILVER\n377,930\n415,723\nFebruary 13, 2024\nUNIT DESCRIPTION\nKILOMETRAGE\nPN / CS\nCOLOR\nBMABB KAUSWAGAN ( Rodolfo N. Pelaez Blvd Brgy. Kauswagan Cagayan de Oro City ) near Office of the City Engineer \nKring : (0927)133-6156 / Basti : (0917)820-8488\nREG BIDDING\nBID NOW\nPRICE\nPRICE\n2023 SUZUKI ERTIGA M/T 1.5 GA-M   [ SLIGHTLY \nBROKEN RIGHT SIDE MIRROR  ]\n7,446\nZAC7071\nWHITE\n557,731\n613,504\n2020 CHERRY  TIGGO 2 A/T 1.5 LUXURY    [ BROKEN \nLEFT DOOR  ]\n65,672\nKAD6577\nRED\n302,540\n332,794\n2018 MAZDA BT 50 M/T 2.2 0 4X2 (D)  \n78,938\nKAB3325\nBLACK\n410,620\n451,682\n2020 MG MG5 A/T 1.5   [ SLIGHT DENT ON HOOD, SLIGHT \nBROKEN HEADLIGHT. UNENCUMBERED CR AND \nUNANNOTATED PNCM  ]\n42,801\nKAD6340\nBLUE\n368,760\n405,636\n2023 SUZUKI CARRY  M/T 1.5 UV   [ Discrepancy of one \ncharacter between CR and on-unit chassis number ]\n5,024\nZAC7955\nWHITE\n404,390\n444,829\n2021 CHEVROLET  SPARK A/T 1.4 LTZ   \n2,482\nMAR6580\nRED\n406,700\n447,370\n2020 KIA SOLUTO A/T 1.4 LX   \n30,233\nKAG1123\nBLUE\n349,580\n384,538\n2022 NISSAN  NAVARA  M/T 2.5 VL 4X4 (D)                                                                    \n[ UNENCUMBERED CR  ]\n44,701\nKAF5578\nWHITE\n881,475\n969,623\n2020 HYUNDAI REINA A/T 1.4 GL   \n52,547\nJAH7956\nBROWN\n283,640\n312,004\n2020 FORD  RANGER A/T 2 0 4X2 (D) [ MINOR \nSCRATCHES & NO TOOLS ]\n111,434\nKAE1364\nALUMINUM \n567,280\n624,008\n2022 MITUSBISHI  MIRAGE G4 M/T 1.2 GLX                                  \n[ UNENCUMBERED CR  ]\n6,791\nKAP2836\nGRAY\n503,532\n553,885\n2021 MG  ZS M/T 1.5 STYLE   [ UNENCUMBERED CR & \nUNANNOTATED PNCM  ]\n89,669\nLAH6725\nWHITE\n286,160\n314,776\n2019 MG  ZS A/T 1.5   [ UNENCUMBERED CR  ]\n46,428\nFAF1887\nBLUE\n305,760\n336,336\n2019 MITSUBISHI  MIRAGE HATCH A/T 1.2 GLX                                              \n[ BRKOKEN, FRONT BUMPER, BROKEN HOOD, \nUNENCUMBERED CR & UNANNOTATED PNCM  ]\n157,294\nKAD3730\nWINE RED\n243,334\n267,668\n2022 CHANGAN  ALSVIN A/T 1.5 0   \n3,972\nN1 P894\nRED\n349,160\n384,076\n2019 MAZDA  2 HATCHBACK A/T 1.5 R                                                     \n[ UNENCUMBERED CR  ]\n39,872\nKAC7113\nTITANIUM \nFLASH \n362,086\n398,295\n2016 HYUNDAI  EON M/T 0.8 GLX   [ BROKEN LEFT \nTAILIGHT  ]\n107,622\nKCU6160\nBLACK\n174,174\n191,591\n2019 CHEVROLET  COLORADO  A/T 2.8 LTZ 4X4                                          \n[ BROKEN LEFT TSIDE MIRROR, BROKEN LEFT FENDER REAR; \nUNENCUMBERED CR & UNANNOTATED PNCM ]\n139,123\nKAC2331\nBLACK\n607,437\n668,181\n2023 MITSUBISHI  MIRAGE HATCH A/T 1.2 GLX                                \n[ UNENCUMBERED CR  ]\n14,453\nLAL4811\nRED\n520,159\n572,175\n2023 MITSUBISHI  MIRAGE G4 A/T 1.2 GLX   [ Damaged \ngear stick ]\n23,813\nKAP6118\nSILVER\n517,322\n569,054\n2018 CHEVROLET TRAX A/T 1.3 LS  [ ENGINE NOT \nWORKING ]\n33,073\nKAD1893\nWHITE\n457,170\n502,887\n2020 KIA  SELTOS  A/T 2 LX   \n50,978\nKAD7230\nORANGE\n541,800\n595,980\n2022 MG ZS A/T 1.5  [ UNANNOTATED PNCM AND \nUNENCUMBERED CR ]\n11,749\nLAJ7585\nRED\n561,190\n617,309\n2022 MG ZS A/T 1.5 STYLE   [ Unencumbered CR  ]\n31,960\nLAJ5735\nBLACK\n409,430\n450,373\n2021 HYUNDAI  TUCSON A/T 2  (D) [ DAMAGED FRONT \nBUMPER ]\n10,542\nLAK8952\nBLACK\n717,990\n789,789\n2022 MG ZS A/T 1.5  [Major dents on the hood and doors. \nBroken front Bumper and windshield. Engine starter for repair]\n30,716\nLAJ4600\nRED\n312,520\n343,772\n2021 GEELY OKAVANGO A/T 1.5 URBAN   \n68,747\nFAF9141\nBLACK\n611,800\n672,980\n2019 MITSUBISHI MIRAGE G4 M/T 1.2 GLX                                                  \n[ UNENCUMBERED CR UNANNOTATED PNCM  ]\n100,572\nZAB5373\nWHITE\n282,949\n311,244\nREG BIDDING\nBID NOW\nPRICE\nPRICE\n2020 NISSAN  NAVARA M/T 2.5 EL 4X2 (D)  [ No battery ]\nNO MILEAGE \nJAD5115\nBROWN\n588,640\n647,504\n2016 HYUNDAI  ACCENT  M/T 1.4 E   [ BROKEN LEFT SIDE \nHEADLIGHT, TAILIGHT, AND SIDE MIRROR ]\n54,978\nMP3050\nSILVER\n219,341\n241,275\nBMABB CAMAMAN-AN [ Pimentel Street Brgy Camaman-an Cagayan de Oro Misamis Oriental ]\nKRING : (0927)133-6156 / BASTI : (0917)820-8488\nUNIT DESCRIPTION\nKILOMETRAGE\nPN / CS\nCOLOR\nBPI ZAMBOANGA VETERANS [ Veterans Avenue, Zamboanga City ]\nKRING : (0927)133-6156 / BASTI : (0917)820-8488\nUNIT DESCRIPTION\nKILOMETRAGE\nPN / CS\nCOLOR\nBuena Mano is a brand owned by Bank of the Philippine Islands, regulated by the Bangko Sentral ng Pilipinas (https://www.bsp.gov.ph).\nMisprints and other errors are unintended and do not constitute acts of misrepresentations, intentional non-disclosure, fraud or withholding of accurate details and pricing.\n"

In [37]:
lines = text.split('\n')
lines[4:]

['2021 SUZUKI ERTIGA M/T 1.5 GL   ',
 '29,155',
 'JAK7175',
 'GRAY',
 '532,707',
 '585,978',
 '2020 NISSAN  URVAN M/T 2.5 0  (D)  [ Broken front ',
 'windshield ]',
 '349,273',
 'JAD9285',
 'WHITE',
 '478,035',
 '525,838',
 '2019 MITSUBISHI STRADA M/T 2.4 GLS 4X2 (D)                                               ',
 '[ UNENCUMBERED CR AND UNANNOTATED PNCM  ]',
 '5,914',
 'KAD5720',
 'SILVER',
 '558,390',
 '614,229',
 '2018 MITSUBISHI MONTERO  A/T 2.4 GLS 4X2 (D)                                  ',
 '[ UNENCUMBERED CR AND UNANNOTATED PNCM, missing ',
 'tail/stoplight ]',
 '41,658',
 'NO PLATE',
 'BLUE',
 '789,889',
 '868,878',
 '2019 NISSAN  NAVARA A/T 2.5 EL 4X2 (D)  [ UNABLE TO ',
 'OPEN HOOD  ]',
 '83,689',
 'JAH8296',
 'BROWN',
 '564,340',
 '620,774',
 '2022 MG MG5 M/T 1.5  [ UNENCUMBERED CR AND ',
 'UNANNOTATED PNCM  ]',
 '13,967',
 'LAK5451',
 'WHITE',
 '315,140',
 '346,654',
 '2020 TOYOTA  VIOS M/T 1.3 J   [ BROKEN LEFT TAILIGHT ',
 ', POOR TRUNK LID CONDITION. UNENCUMBERED CR  ]',
 '145,534',
 'GAO1646',
 'WHITE',
 '294,724',
 '324,197',
 '2018 MITSUBISHI MIRAGE G4 A/T 1.2 GLX   [ BROKEN ',
 'LEFT TAILIGHT AND LEFT HEADLIGHT, UNENCUMBERED CR  ]',
 '55,730',
 'KAB8123',
 'GRAY',
 '261,064',
 '287,171',
 '2020 CHEVROLET  COLORADO  A/T 2.8 TRAIL BOSS 4X2 ',
 '(D) [ NO SPARE TIRE & TOOLS ]',
 '117,640',
 'KAF8625',
 'BROWN',
 '583,977',
 '642,374',
 '2023 KIA SOLUTO A/T 1.4 LX   [ UNENCUMBERED CR  ]',
 '9,729',
 'XOT739',
 'BEIGE',
 '420,210',
 '462,231',
 '2021 TOYOTA  VIOS A/T 1.3 XLE   [ WITH 1 LETTER ',
 'DIFFERENCE IN ACTUAL PLATE NUMBER AND CR PLATE NUMBER ]',
 '76,735',
 'GAU8837',
 'SILVER',
 '485,959',
 '534,555',
 '2016 FOTON TORNADO  M/T 4.5 DROPSIDE 4X2 (D)                                      ',
 '[ UNENCUMBERED CR , BROKEN DOOR LOCKS  ]',
 '85,405',
 'KAA1291',
 'WHITE',
 '259,910',
 '285,901',
 '2019 CHEVROLET  COLORADO  M/T 2.5 LT 4X2 (D)                                     ',
 '[ UNENCUMBERED CR, BROKEN TRUN K DOOR  ]',
 '91,966',
 'FAG5565',
 'SILVER',
 '511,056',
 '562,162',
 '2020 MG  MG5 A/T 1.5   [ FRONT BUMPER COLLISION  ]',
 '34,858',
 'NGD2252',
 'BLUE',
 '321,580',
 '353,738',
 '2016 HYUNDAI  EON M/T 0.8 GLX   [ WITH 1 LETTER ',
 'DIFFERENCE IN ACTUAL PLATE NUMBER AND CR PLATE NUMBER ]',
 '11,904',
 'KDO6435',
 'RED',
 '176,656',
 '194,322',
 '2018 FORD RANGER A/T 2.2 0 4X2 (D) [ MINOR ',
 'SCRATCHES ]',
 '113,683',
 'ZAA8101',
 'BLACK',
 '557,480',
 '613,228',
 '2020 KIA  SOLUTO M/T 1.4 LX   [ Unencumbered CR; ',
 'Annotated PNCM ]',
 '79,880',
 'KAD4511',
 'WHITE',
 '209,790',
 '230,769',
 '2020 FORD  ECOSPORT  M/T 1.5 TREND   ',
 '11,980',
 'ZAB7982',
 'RED',
 '425,600',
 '468,160',
 '2017 MITSUBISHI  MIRAGE G4 M/T 1.2 GLX                                                 ',
 '[ Unannotated PNCM and Unencumbered CR  ]',
 '46,406',
 'KAB4954',
 'RED',
 '258,700',
 '284,570',
 '2022 MITSUBISHI MIRAGE G4 A/T 1.2 GLX                                             ',
 '[ UNANNOTATED PNCM  ]',
 '10,595',
 'NFK6246',
 'RED',
 '475,006',
 '522,507',
 '2019 Hyundai  Accent M/T 1.4 GL   [ BROKEN FRONT ',
 'BUMPER AND TRUNK LID RUSTING ]',
 '76,127',
 'JAC7712',
 'WHITE',
 '221,520',
 '243,672',
 '2021 TOYOTA  VIOS A/T 1.3 XLE    ',
 '25,544',
 'GAV7392',
 'GARYISH BLUE',
 '537,263',
 '590,989',
 '2021 GEELY COOLRAY  A/T 1.5 SPORTS   ',
 '28,133',
 'FAI3602',
 'RED',
 '602,980',
 '663,278',
 '2020 CHEVROLET  COLORADO A/T 2.8 LTZ 4X4 (D)                           ',
 '[Broken Front bumper and side fender. Slightly broken rear bumper]',
 '88,788',
 'KAG1209',
 'WHITE',
 '596,505',
 '656,156',
 '2019 MG ZS A/T 1.5 STYLE   ',
 '41,578',
 'FAG1543',
 'ORANGE',
 '406,840',
 '447,524',
 '2020 NISSAN  ALMERA A/T 1.2 LE   [ Unannotated PNCM ',
 'and unencumbered CR  ]',
 '95,025',
 'KAF8718',
 'BROWN',
 '269,368',
 '296,305',
 "2022 MG MG5 M/T 1.5   [ Broken driver's side door lock, ",
 'Broken front Right window side  ]',
 '21,786',
 'LAK3170',
 'RED',
 '309,725',
 '340,698',
 '2023 NISSAN  LIVINA A/T 1.5 VE   ',
 '18,370',
 'GAK4191',
 'SILVER',
 '725,970',
 '798,567',
 '2022 MITSUBISHI MIRAGE G4 M/T 1.2 GLX                                            ',
 '[ Unannotated PNCM and unencumbered CR  ]',
 '19,810',
 'KAP5148',
 'SILVER',
 '377,930',
 '415,723',
 'February 13, 2024',
 'UNIT DESCRIPTION',
 'KILOMETRAGE',
 'PN / CS',
 'COLOR',
 'BMABB KAUSWAGAN ( Rodolfo N. Pelaez Blvd Brgy. Kauswagan Cagayan de Oro City ) near Office of the City Engineer ',
 'Kring : (0927)133-6156 / Basti : (0917)820-8488',
 'REG BIDDING',
 'BID NOW',
 'PRICE',
 'PRICE',
 '2023 SUZUKI ERTIGA M/T 1.5 GA-M   [ SLIGHTLY ',
 'BROKEN RIGHT SIDE MIRROR  ]',
 '7,446',
 'ZAC7071',
 'WHITE',
 '557,731',
 '613,504',
 '2020 CHERRY  TIGGO 2 A/T 1.5 LUXURY    [ BROKEN ',
 'LEFT DOOR  ]',
 '65,672',
 'KAD6577',
 'RED',
 '302,540',
 '332,794',
 '2018 MAZDA BT 50 M/T 2.2 0 4X2 (D)  ',
 '78,938',
 'KAB3325',
 'BLACK',
 '410,620',
 '451,682',
 '2020 MG MG5 A/T 1.5   [ SLIGHT DENT ON HOOD, SLIGHT ',
 'BROKEN HEADLIGHT. UNENCUMBERED CR AND ',
 'UNANNOTATED PNCM  ]',
 '42,801',
 'KAD6340',
 'BLUE',
 '368,760',
 '405,636',
 '2023 SUZUKI CARRY  M/T 1.5 UV   [ Discrepancy of one ',
 'character between CR and on-unit chassis number ]',
 '5,024',
 'ZAC7955',
 'WHITE',
 '404,390',
 '444,829',
 '2021 CHEVROLET  SPARK A/T 1.4 LTZ   ',
 '2,482',
 'MAR6580',
 'RED',
 '406,700',
 '447,370',
 '2020 KIA SOLUTO A/T 1.4 LX   ',
 '30,233',
 'KAG1123',
 'BLUE',
 '349,580',
 '384,538',
 '2022 NISSAN  NAVARA  M/T 2.5 VL 4X4 (D)                                                                    ',
 '[ UNENCUMBERED CR  ]',
 '44,701',
 'KAF5578',
 'WHITE',
 '881,475',
 '969,623',
 '2020 HYUNDAI REINA A/T 1.4 GL   ',
 '52,547',
 'JAH7956',
 'BROWN',
 '283,640',
 '312,004',
 '2020 FORD  RANGER A/T 2 0 4X2 (D) [ MINOR ',
 'SCRATCHES & NO TOOLS ]',
 '111,434',
 'KAE1364',
 'ALUMINUM ',
 '567,280',
 '624,008',
 '2022 MITUSBISHI  MIRAGE G4 M/T 1.2 GLX                                  ',
 '[ UNENCUMBERED CR  ]',
 '6,791',
 'KAP2836',
 'GRAY',
 '503,532',
 '553,885',
 '2021 MG  ZS M/T 1.5 STYLE   [ UNENCUMBERED CR & ',
 'UNANNOTATED PNCM  ]',
 '89,669',
 'LAH6725',
 'WHITE',
 '286,160',
 '314,776',
 '2019 MG  ZS A/T 1.5   [ UNENCUMBERED CR  ]',
 '46,428',
 'FAF1887',
 'BLUE',
 '305,760',
 '336,336',
 '2019 MITSUBISHI  MIRAGE HATCH A/T 1.2 GLX                                              ',
 '[ BRKOKEN, FRONT BUMPER, BROKEN HOOD, ',
 'UNENCUMBERED CR & UNANNOTATED PNCM  ]',
 '157,294',
 'KAD3730',
 'WINE RED',
 '243,334',
 '267,668',
 '2022 CHANGAN  ALSVIN A/T 1.5 0   ',
 '3,972',
 'N1 P894',
 'RED',
 '349,160',
 '384,076',
 '2019 MAZDA  2 HATCHBACK A/T 1.5 R                                                     ',
 '[ UNENCUMBERED CR  ]',
 '39,872',
 'KAC7113',
 'TITANIUM ',
 'FLASH ',
 '362,086',
 '398,295',
 '2016 HYUNDAI  EON M/T 0.8 GLX   [ BROKEN LEFT ',
 'TAILIGHT  ]',
 '107,622',
 'KCU6160',
 'BLACK',
 '174,174',
 '191,591',
 '2019 CHEVROLET  COLORADO  A/T 2.8 LTZ 4X4                                          ',
 '[ BROKEN LEFT TSIDE MIRROR, BROKEN LEFT FENDER REAR; ',
 'UNENCUMBERED CR & UNANNOTATED PNCM ]',
 '139,123',
 'KAC2331',
 'BLACK',
 '607,437',
 '668,181',
 '2023 MITSUBISHI  MIRAGE HATCH A/T 1.2 GLX                                ',
 '[ UNENCUMBERED CR  ]',
 '14,453',
 'LAL4811',
 'RED',
 '520,159',
 '572,175',
 '2023 MITSUBISHI  MIRAGE G4 A/T 1.2 GLX   [ Damaged ',
 'gear stick ]',
 '23,813',
 'KAP6118',
 'SILVER',
 '517,322',
 '569,054',
 '2018 CHEVROLET TRAX A/T 1.3 LS  [ ENGINE NOT ',
 'WORKING ]',
 '33,073',
 'KAD1893',
 'WHITE',
 '457,170',
 '502,887',
 '2020 KIA  SELTOS  A/T 2 LX   ',
 '50,978',
 'KAD7230',
 'ORANGE',
 '541,800',
 '595,980',
 '2022 MG ZS A/T 1.5  [ UNANNOTATED PNCM AND ',
 'UNENCUMBERED CR ]',
 '11,749',
 'LAJ7585',
 'RED',
 '561,190',
 '617,309',
 '2022 MG ZS A/T 1.5 STYLE   [ Unencumbered CR  ]',
 '31,960',
 'LAJ5735',
 'BLACK',
 '409,430',
 '450,373',
 '2021 HYUNDAI  TUCSON A/T 2  (D) [ DAMAGED FRONT ',
 'BUMPER ]',
 '10,542',
 'LAK8952',
 'BLACK',
 '717,990',
 '789,789',
 '2022 MG ZS A/T 1.5  [Major dents on the hood and doors. ',
 'Broken front Bumper and windshield. Engine starter for repair]',
 '30,716',
 'LAJ4600',
 'RED',
 '312,520',
 '343,772',
 '2021 GEELY OKAVANGO A/T 1.5 URBAN   ',
 '68,747',
 'FAF9141',
 'BLACK',
 '611,800',
 '672,980',
 '2019 MITSUBISHI MIRAGE G4 M/T 1.2 GLX                                                  ',
 '[ UNENCUMBERED CR UNANNOTATED PNCM  ]',
 '100,572',
 'ZAB5373',
 'WHITE',
 '282,949',
 '311,244',
 'REG BIDDING',
 'BID NOW',
 'PRICE',
 'PRICE',
 '2020 NISSAN  NAVARA M/T 2.5 EL 4X2 (D)  [ No battery ]',
 'NO MILEAGE ',
 'JAD5115',
 'BROWN',
 '588,640',
 '647,504',
 '2016 HYUNDAI  ACCENT  M/T 1.4 E   [ BROKEN LEFT SIDE ',
 'HEADLIGHT, TAILIGHT, AND SIDE MIRROR ]',
 '54,978',
 'MP3050',
 'SILVER',
 '219,341',
 '241,275',
 'BMABB CAMAMAN-AN [ Pimentel Street Brgy Camaman-an Cagayan de Oro Misamis Oriental ]',
 'KRING : (0927)133-6156 / BASTI : (0917)820-8488',
 'UNIT DESCRIPTION',
 'KILOMETRAGE',
 'PN / CS',
 'COLOR',
 'BPI ZAMBOANGA VETERANS [ Veterans Avenue, Zamboanga City ]',
 'KRING : (0927)133-6156 / BASTI : (0917)820-8488',
 'UNIT DESCRIPTION',
 'KILOMETRAGE',
 'PN / CS',
 'COLOR',
 'Buena Mano is a brand owned by Bank of the Philippine Islands, regulated by the Bangko Sentral ng Pilipinas (https://www.bsp.gov.ph).',
 'Misprints and other errors are unintended and do not constitute acts of misrepresentations, intentional non-disclosure, fraud or withholding of accurate details and pricing.',
 '']

## Extract Data

In [40]:
def extract_data(lines):
    entry = ' '.join(lines)
    pattern = re.compile(
        r'''(\d{4})  # Year
        \s+(.*)  # Unit Description
        \s+(NO\sMILEAGE|unverified|-|N/A|(?:\d{1,3}(?:,\d{3})*)) # Kilometrage
        \s+([\w/\d]+(?:\s*/\s*[\w/\d]+)?) # PN/CS
        \s+([\w\s/]+) # Color
        \s+((?:\d{1,3}(?:,\d{3})*)) # Reg Bidding Price
        \s+((?:\d{1,3}(?:,\d{3})*)) # Bid Now Price''',
        re.VERBOSE
    )
    match = pattern.search(entry)
    if match:
        return match.groups()
    return None

data = []
temp_lines = []

for line in lines:
    # Check if the line starts with a year (assuming it starts a new entry)
    if re.match(r"\d{4}", line):
        if temp_lines:
            parsed_data = extract_data(temp_lines)
            if parsed_data:
                data.append(parsed_data)
            temp_lines = []

    # Append the current line to temp_lines
    temp_lines.append(line)

# Process the last accumulated lines
if temp_lines:
    parsed_data = extract_data(temp_lines)
    if (parsed_data):
        data.append(parsed_data)

# Define the column names
columns = ["year", "unit_description", "kilometrage", "pn/cs", "color", "reg_bidding_price", "bid_now_price"]

# Create a DataFrame from the extracted data
df = pd.DataFrame(data, columns=columns)

#Add Transmission

for index, row in df.iterrows():
  if 'M/T' in row['unit_description']:
    df.at[index, 'transmission'] = 'M/T'
  elif 'A/T' in row['unit_description']:
    df.at[index, 'transmission'] = 'A/T'

# Display the DataFrame
df

,year,unit_description,kilometrage,pn/cs,color,reg_bidding_price,bid_now_price,transmission
0,2021,SUZUKI ERTIGA M/T 1.5 GL,"29,155",JAK7175,GRAY,"532,707","585,978",M/T
1,2020,NISSAN URVAN M/T 2.5 0 (D) [ Broken front ...,"349,273",JAD9285,WHITE,"478,035","525,838",M/T
2,2019,MITSUBISHI STRADA M/T 2.4 GLS 4X2 (D) ...,"5,914",KAD5720,SILVER,"558,390","614,229",M/T
3,2018,MITSUBISHI MONTERO A/T 2.4 GLS 4X2 (D) ...,"41,658",NO,PLATE BLUE,"789,889","868,878",A/T
4,2019,NISSAN NAVARA A/T 2.5 EL 4X2 (D) [ UNABLE TO...,"83,689",JAH8296,BROWN,"564,340","620,774",A/T
5,2022,MG MG5 M/T 1.5 [ UNENCUMBERED CR AND UNANNOT...,"13,967",LAK5451,WHITE,"315,140","346,654",M/T
6,2020,TOYOTA VIOS M/T 1.3 J [ BROKEN LEFT TAILIGH...,"145,534",GAO1646,WHITE,"294,724","324,197",M/T
7,2018,MITSUBISHI MIRAGE G4 A/T 1.2 GLX [ BROKEN L...,"55,730",KAB8123,GRAY,"261,064","287,171",A/T
8,2020,CHEVROLET COLORADO A/T 2.8 TRAIL BOSS 4X2 (...,"117,640",KAF8625,BROWN,"583,977","642,374",A/T
9,2023,KIA SOLUTO A/T 1.4 LX [ UNENCUMBERED CR ],"9,729",XOT739,BEIGE,"420,210","462,231",A/T
10,2021,TOYOTA VIOS A/T 1.3 XLE [ WITH 1 LETTER DI...,"76,735",GAU8837,SILVER,"485,959","534,555",A/T
11,2016,FOTON TORNADO M/T 4.5 DROPSIDE 4X2 (D) ...,"85,405",KAA1291,WHITE,"259,910","285,901",M/T
12,2019,CHEVROLET COLORADO M/T 2.5 LT 4X2 (D) ...,"91,966",FAG5565,SILVER,"511,056","562,162",M/T
13,2020,MG MG5 A/T 1.5 [ FRONT BUMPER COLLISION ],"34,858",NGD2252,BLUE,"321,580","353,738",A/T
14,2016,HYUNDAI EON M/T 0.8 GLX [ WITH 1 LETTER DI...,"11,904",KDO6435,RED,"176,656","194,322",M/T
15,2018,FORD RANGER A/T 2.2 0 4X2 (D) [ MINOR SCRATCH...,"113,683",ZAA8101,BLACK,"557,480","613,228",A/T
16,2020,KIA SOLUTO M/T 1.4 LX [ Unencumbered CR; A...,"79,880",KAD4511,WHITE,"209,790","230,769",M/T
17,2020,FORD ECOSPORT M/T 1.5 TREND,"11,980",ZAB7982,RED,"425,600","468,160",M/T
18,2017,MITSUBISHI MIRAGE G4 M/T 1.2 GLX ...,"46,406",KAB4954,RED,"258,700","284,570",M/T
19,2022,MITSUBISHI MIRAGE G4 A/T 1.2 GLX ...,"10,595",NFK6246,RED,"475,006","522,507",A/T
20,2019,Hyundai Accent M/T 1.4 GL [ BROKEN FRONT B...,"76,127",JAC7712,WHITE,"221,520","243,672",M/T
21,2021,TOYOTA VIOS A/T 1.3 XLE,"25,544",GAV7392,GARYISH BLUE,"537,263","590,989",A/T
22,2021,GEELY COOLRAY A/T 1.5 SPORTS,"28,133",FAI3602,RED,"602,980","663,278",A/T
23,2020,CHEVROLET COLORADO A/T 2.8 LTZ 4X4 (D) ...,"88,788",KAG1209,WHITE,"596,505","656,156",A/T
24,2019,MG ZS A/T 1.5 STYLE,"41,578",FAG1543,ORANGE,"406,840","447,524",A/T
25,2020,NISSAN ALMERA A/T 1.2 LE [ Unannotated PNCM...,"95,025",KAF8718,BROWN,"269,368","296,305",A/T
26,2022,MG MG5 M/T 1.5 [ Broken driver's side door l...,"21,786",LAK3170,RED,"309,725","340,698",M/T
27,2023,NISSAN LIVINA A/T 1.5 VE,"18,370",GAK4191,SILVER,"725,970","798,567",A/T
28,2022,MITSUBISHI MIRAGE G4 M/T 1.2 GLX ...,"19,810",KAP5148,SILVER,"377,930","415,723",M/T
29,2023,SUZUKI ERTIGA M/T 1.5 GA-M [ SLIGHTLY BROKE...,"7,446",ZAC7071,WHITE,"557,731","613,504",M/T
30,2020,CHERRY TIGGO 2 A/T 1.5 LUXURY [ BROKEN LE...,"65,672",KAD6577,RED,"302,540","332,794",A/T
31,2018,MAZDA BT 50 M/T 2.2 0 4X2 (D),"78,938",KAB3325,BLACK,"410,620","451,682",M/T
32,2020,"MG MG5 A/T 1.5 [ SLIGHT DENT ON HOOD, SLIGHT...","42,801",KAD6340,BLUE,"368,760","405,636",A/T
33,2023,SUZUKI CARRY M/T 1.5 UV [ Discrepancy of on...,"5,024",ZAC7955,WHITE,"404,390","444,829",M/T
34,2021,CHEVROLET SPARK A/T 1.4 LTZ,"2,482",MAR6580,RED,"406,700","447,370",A/T
35,2020,KIA SOLUTO A/T 1.4 LX,"30,233",KAG1123,BLUE,"349,580","384,538",A/T
36,2022,NISSAN NAVARA M/T 2.5 VL 4X4 (D) ...,"44,701",KAF5578,WHITE,"881,475","969,623",M/T
37,2020,HYUNDAI REINA A/T 1.4 GL,"52,547",JAH7956,BROWN,"283,640","312,004",A/T
38,2020,FORD RANGER A/T 2 0 4X2 (D) [ MINOR SCRATCHE...,"111,434",KAE1364,ALUMINUM,"567,280","624,008",A/T
39,2022,MITUSBISHI MIRAGE G4 M/T 1.2 GLX ...,"6,791",KAP2836,GRAY,"503,532","553,885",M/T
40,2021,MG ZS M/T 1.5 STYLE [ UNENCUMBERED CR & UN...,"89,669",LAH6725,WHITE,"286,160","314,776",M/T
41,2019,MG ZS A/T 1.5 [ UNENCUMBERED CR ],"46,428",FAF1887,BLUE,"305,760","336,336",A/T
42,2019,MITSUBISHI MIRAGE HATCH A/T 1.2 GLX ...,"157,294",KAD3730,WINE RED,"243,334","267,668",A/T
43,2022,CHANGAN ALSVIN A/T 1.5 0,"3,972",N1,P894 RED,"349,160","384,076",A/T
44,2019,MAZDA 2 HATCHBACK A/T 1.5 R ...,"39,872",KAC7113,TITANIUM FLASH,"362,086","398,295",A/T
45,2016,HYUNDAI EON M/T 0.8 GLX [ BROKEN LEFT TAIL...,"107,622",KCU6160,BLACK,"174,174","191,591",M/T
46,2019,CHEVROLET COLORADO A/T 2.8 LTZ 4X4 ...,"139,123",KAC2331,BLACK,"607,437","668,181",A/T
47,2023,MITSUBISHI MIRAGE HATCH A/T 1.2 GLX ...,"14,453",LAL4811,RED,"520,159","572,175",A/T
48,2023,MITSUBISHI MIRAGE G4 A/T 1.2 GLX [ Damaged ...,"23,813",KAP6118,SILVER,"517,322","569,054",A/T
49,2018,CHEVROLET TRAX A/T 1.3 LS [ ENGINE NOT WORKI...,"33,073",KAD1893,WHITE,"457,170","502,887",A/T
50,2020,KIA SELTOS A/T 2 LX,"50,978",KAD7230,ORANGE,"541,800","595,980",A/T
51,2022,MG ZS A/T 1.5 [ UNANNOTATED PNCM AND UNENCUM...,"11,749",LAJ7585,RED,"561,190","617,309",A/T
52,2022,MG ZS A/T 1.5 STYLE [ Unencumbered CR ],"31,960",LAJ5735,BLACK,"409,430","450,373",A/T
53,2021,HYUNDAI TUCSON A/T 2 (D) [ DAMAGED FRONT BU...,"10,542",LAK8952,BLACK,"717,990","789,789",A/T
54,2022,MG ZS A/T 1.5 [Major dents on the hood and do...,"30,716",LAJ4600,RED,"312,520","343,772",A/T
55,2021,GEELY OKAVANGO A/T 1.5 URBAN,"68,747",FAF9141,BLACK,"611,800","672,980",A/T
56,2019,MITSUBISHI MIRAGE G4 M/T 1.2 GLX ...,"100,572",ZAB5373,WHITE,"282,949","311,244",M/T
57,2020,NISSAN NAVARA M/T 2.5 EL 4X2 (D) [ No battery ],NO MILEAGE,JAD5115,BROWN,"588,640","647,504",M/T
58,2016,HYUNDAI ACCENT M/T 1.4 E [ BROKEN LEFT SID...,"54,978",MP3050,SILVER,"219,341","241,275",M/T

In [39]:
test = ['2020 NISSAN  NAVARA M/T 2.5 EL 4X2 (D)  [ No battery ]',
 'NO MILEAGE ',
 'JAD5115',
 'BROWN',
 '588,640',
 '647,504']

test1 = ['2022 Changan CS35 A/T 1.4L Plus 7DCT Luxe   [ No seat ',
 'covers. LTO Cebu City-registered. Cancellation of mortgage is ',
 'at RD-Negros Oriental. ]',
 '15,378',
 'N1P916',
 'White',
 '535,990',
 '589,589']


data = []
temp_lines = []

for line in test:
    # Check if the line starts with a year (assuming it starts a new entry)
    if re.match(r"\d{4}", line):
        if temp_lines:
            parsed_data = extract_data(temp_lines)
            if parsed_data:
                data.append(parsed_data)
            temp_lines = []

    # Append the current line to temp_lines
    temp_lines.append(line)

# Process the last accumulated lines
if temp_lines:
    parsed_data = extract_data(temp_lines)
    if parsed_data:
        data.append(parsed_data)

print(data)

[('2020', 'NISSAN  NAVARA M/T 2.5 EL 4X2 (D)  [ No battery ]', 'N/A', 'JAD5115', 'BROWN', '588,640', '647,504')]

In [72]:
locations = ['bacolod', 'cagayan_de_oro', 'cebu', 'dagupan', 'davao', 'guiguinto', 'iloilo', 'lipa', 'naga', 'san_fernando']
dfs = []
#Extract Data Function
def extract_data(lines):
    entry = ' '.join(lines)
    pattern = re.compile(
        r'''(\d{4})  # Year
        \s+(.*)  # Unit Description
        \s+(NO\sMILEAGE|unverified|-|N/A|(?:\d{1,3}(?:,\d{3})*)) # Kilometrage
        \s+([\d\s/]+|[\w/\d]+(?:\s*/\s*[\w/\d]+)?) # PN/CS
        \s+([\w\s/]+) # Color
        \s+((?:\d{1,3}(?:,\d{3})*)) # Reg Bidding Price
        \s+((?:\d{1,3}(?:,\d{3})*)) # Bid Now Price''',
        re.VERBOSE
    )
    match = pattern.search(entry)
    if match:
        return match.groups()
    return None

for loc in locations:

  #Read PDF File
  pdf_document = f'/content/drive/MyDrive/Webscraping Datasets (BPI)/{loc}.pdf'
  pdf = fitz.open(pdf_document)

  #Extract Text
  text = ""
  for page_num in range(len(pdf)):
      page = pdf.load_page(page_num)
      text += page.get_text()
  lines = text.split('\n')

  #Extract Data
  data = []
  temp_lines = []

  for line in lines:
      # Check if the line starts with a year (assuming it starts a new entry)
      if re.match(r"\d{4}", line):
          if temp_lines:
              parsed_data = extract_data(temp_lines)
              if parsed_data:
                  data.append(parsed_data)
              temp_lines = []

      # Append the current line to temp_lines
      temp_lines.append(line)

  # Process the last accumulated lines
  if temp_lines:
      parsed_data = extract_data(temp_lines)
      if (parsed_data):
          data.append(parsed_data)

  # Define the column names
  columns = ["year", "unit_description", "kilometrage", "pn/cs", "color", "reg_bidding_price", "bid_now_price"]

  # Create a DataFrame from the extracted data
  exec('df_{} = pd.DataFrame(data, columns=columns)'.format(loc))
  exec('dfs.append(df_{})'.format(loc))

In [68]:
df_cebu

,year,unit_description,kilometrage,pn/cs,color,reg_bidding_price,bid_now_price
0,2023,Chery Tiggo 7 Pro A/T 1.5L [ Lapu-Lapu ],"6,198",GAK9642,Red,"842,100","926,310"
1,2022,Chery Tiggo 7 A/T 1.5L Pro,"20,232",GAS5001,RED,"594,000","653,400"
2,2023,Geely Emgrand Premium A/T 1.5L,"3,186",GBA6598,GREY,"755,175","830,693"
3,2007,Kia Picanto M/T 1.6L,"139,132",YFP796,Red,"76,200","83,820"
4,2023,Kia Motors Stonic A/T 1.4L LX,"2,817",GBA2538,White,"660,800","726,880"
5,2022,MG ZS T A/T 1.3L [ Leyte Registered ],"7,530",HAG3740,Black,"675,000","742,500"
6,2022,MG MG5 M/T 1.5L [ Leyte registered ],"17,413",HAG1280,White,"361,200","397,320"
7,2022,MG MG5 M/T 1.5L,"12,583",GAR1626,BLACK,"338,325","372,158"
8,2021,MG ZS A/T 1.5L,"22,585",GAW1139,RED,"458,325","504,158"
9,2022,Mirage Mitsubishi A/T 1.2L GLX G,"13,221",GAW3053,TITANIUM GRAY METALLIC,"400,125","440,138"
10,2015,Mitsubishi Adventure M/T 2.5L GLS S (D) ...,"23,857",KCB4722,Black,"290,500","319,550"
11,2018,Mitsubishi Strada M/T 2.4L GLS (D) [ No ID of...,"171,113",HAB3118,DIAMOND BLACK,"389,700","428,670"
12,2023,Mitsubishi Mirage A/T 1.2L G4 GLX 1,"11,320",GAK4639,RED METALLIC,"446,550","491,205"
13,2022,Mitsubishi Mirage A/T 1.2L G,"15,888",GAR6373,TITANIUM GRAY,"381,000","419,100"
14,2022,Mitsubishi Mirage A/T 1.2L G4 GLX 1,"42,084",GAW6594,COOL SILVER METALLIC,"412,500","453,750"
15,2021,Mitsubishi Xpander A/T 1.5L GLS [ Leyte Reg...,"14,985",HAC1256,STERLING SILVER METALLIC,"671,700","738,870"
16,2022,Mitsubishi Mirage A/T 1.2L G4 GLX 1 [ No ID ...,"10,673",GAW9723,RED,"414,000","455,400"
17,2023,Mitsubishi Strada A/T 2.4L GLS (D) [ No ID of...,"9,973",GAK1554,RED SOLID CLEAR,"887,925","976,718"
18,2016,Nissan NP300 Navara A/T 2.5L EL (D),"108,317",AEC7383,Orange,"481,600","529,760"
19,2021,Nissan Navara A/T 2.5L VL (D),"30,912",GAT9129,LUNAR METALLIC GRAY,"873,000","960,300"
20,2019,Nissan Sylphy B17 A/T 1.6L C,"33,308",GAU1232,White,"403,900","444,290"
21,2022,Nissan Almera A/T 1.0L VE T [ No ID of pre...,"29,548",HAG1611,Silver,"585,200","643,720"
22,2019,Nissan Navara M/T 2.5L EL (D),"29,115",F1N148,ALPINE WHITE,"622,875","685,163"
23,2022,Rush Toyota M/T 1.5L E,"14,173",GAW8757,WHITE,"600,375","660,413"
24,2022,Suzuki XL7 A/T 1.5L GLX,"21,504",GAW6345,ORANGE,"669,300","736,230"
25,2018,Suzuki Ciaz M/T 1.4L GL [ Leyte Registered ],"154,149",HAA8054,GRAY,"268,050","294,855"
26,2019,Toyota Wigo A/T 1.0L TRD,"17,959",GAP9410,Gray,"256,200","281,820"
27,2019,Toyota Innova M/T 2.8L J DI (D) [ No ID of ...,"97,524",GAL4634,White,"485,800","534,380"
28,2019,Toyota Vios M/T 1.3L J,"49,087",GAJ3434,Thermalyte,"261,100","287,210"
29,2018,Toyota Vios A/T 1.3L E,"121,061",GAG1665,Blackish Red,"325,425","357,968"
30,2015,Toyota Innova A/T 2.5L E (D) [ Bohol Regist...,"168,146",ABY7415,Thermalyte,"417,200","458,920"
31,2019,Toyota Vios A/T 1.3L XE CVT [ Bohol Regist...,"42,099",GAL5648,White,"361,200","397,320"
32,2021,Toyota Vios A/T 1.3L XE CVT,"42,103",GAU5672,White,"364,700","401,170"
33,2022,Toyota Vios A/T 1.3L XLE CV,"12,273",GAV8557,ALUMINA JADE METALLIC,"491,475","540,623"
34,2012,Toyota Fortuner M/T 2.5L 4X2 (D),"203,869",YKN439,WHITE,"428,100","470,910"
35,2022,Toyota Wigo A/T 1.0L G [ No ID of prev owner ],"14,142",GAV8791,SILVER METALLIC,"381,000","419,100"
36,2022,Mitsubishi Mirage M/T 1.2L G,"8,135",GAS4121,TITANIUM GRAY METALLIC,"349,440","384,384"
37,2023,Nissan Livina A/T 1.5L VE,"4,284",GBA2711,BLACK,"731,680","804,848"
38,2021,Toyota Innova A/T 2.8L E DI Wagon (D),"38,971",GAT9439,BLACK,"818,160","899,976"
39,2022,Changan Alsvin A/T 1.5L,"2,063",GAR3361,RED,"379,040","416,944"
40,2023,MG ZS A/T 1.5L [ Leyte Registered ],"19,937",GAK1585,BLACK,"740,560","814,616"
41,2020,Mitsubishi Mirage A/T 1.2L G4 GLX 1 [ No ID ...,"27,597",GAU3408,WINE RED PEARL,"356,800","392,480"
42,2018,Mitsubishi Mirage A/T 1.2L G4 GLX [ Leyte ...,"28,311",HAB4106,VIRGIL GRAY,"275,840","303,424"
43,2021,Nissan Navara A/T 2.5L VE (D) [ No ID of prev...,"30,891",GAV7956,WHITE,"919,440","1,011,384"
44,2019,Suzuki Dzire A/T 1.2L GL [ No ID of prev own...,"60,028",HAB3928,GRAY,"325,280","357,808"
45,2022,Toyota Rush A/T 1.5L G [ No ID of prev owner ],"15,119",GAV7316,White,"744,800","819,280"
46,2022,Toyota Rush A/T 1.5L G [ No ID of prev owner ],"18,865",GAV9659,White,"698,080","767,888"
47,2017,Mitsubishi Adventure M/T 2.5L GLS S (D),"32,519",GAB3793,POLAR WHITE,"359,200","395,120"
48,2019,Toyota Avanza M/T 1.3L E [ No ID of prev own...,"40,454",GAM9980,GRAY METALLIC,"442,080","486,288"
49,2019,Toyota Vios A/T 1.3L E [ No ID of prev owner ],"31,577",GAL1401,BLACKISH RED MICA,"405,680","446,248"
50,2013,Toyota Vios M/T 1.3L J,"68,274",VFU228,THERMALYTE,"205,200","225,720"
51,2016,Toyota Wigo A/T 1.0L G,"101,840",ACS2512,Dark Blue Mica Metallic,"277,600","305,360"

In [ ]:
'''
bacolod = 21 /
cagayan_de_oro = 59 /
cebu = 54 X (missing the 2 rows with pn/cs 130107 - 52)
dagupan = 10 /
davao = 38 /
guiguinto = 34 /
iloilo = 37 /
lipa = 16 /
naga = 2 /
san_fernando = 17 X (missing the row with no kilometrage - 16)
'''

## Concatenate Dataframes

In [77]:
df_concat = pd.concat(dfs)
df_concat

,year,unit_description,kilometrage,pn/cs,color,reg_bidding_price,bid_now_price
0,2022,Changan CS35 A/T 1.4L Plus 7DCT Luxe [ No se...,"15,378",N1P916,White,"535,990","589,589"
1,2021,Chery Tiggo5x A/T 1.5L Comfort 5STR ...,"23,288",FAF2671,Blue,"337,350","371,085"
2,2021,Hyundai Accent M/T 1.4L GL [ LTO Pontevedra-...,"77,161",FAI8306,Silver,"407,170","447,887"
3,2020,Hyundai Accent A/T 1.4L GL [ Car's aircon is...,"33,291",FAI3373,Red,"479,340","527,274"
4,2021,Maxus G50 A/T 1.5L Elite Turbo DCT [ No tool...,"30,596",FAI5987,White,"538,980","592,878"
...,...,...,...,...,...,...,...
11,2021,Geely Okavango A/T 1500 Urban [ unencumbered...,"22,164",CAX3077,Black,"848,700","933,570"
12,2024,Mitsubishi L300 M/T 2268 FB EXCEED 2.2D w/ du...,"2,939",Y3S699,Polar White,"987,000","1,085,700"
13,2020,Mitsubishi L300 M/T 2268 FB (Head only) (D) ...,"110,993",CAV8858,White,"302,400","332,640"
14,2023,Toyota Wigo A/T 998 1.0G,"13,436",CBE5969,Yellow,"526,050","578,655"
15,2021,Toyota Vios A/T 1329 1.3 XLE CVT,"64,808",NEP9741,Red Mica Metallic,"460,950","507,045"